name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean workspace
        run: git clean -fdx

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install Dependencies
        # Note: If you add new dependencies, run 'pnpm install' locally and commit pnpm-lock.yaml
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Build Packages
        run: pnpm run build

      - name: Run Unit Tests (Vitest)
        run: pnpm run test:unit

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Debug App Start (if Playwright fails)
        if: failure()
        run: |
          echo "App start logs:"
          cat ./apps/web/.next/trace | tail -n 100 || echo "No trace file found."

      - name: Run Playwright Tests
        run: pnpm exec playwright test

      - name: Upload Playwright Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
